In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = pd.read_csv(r'C:\Users\HP\Downloads\songs_complete_data.csv')
pd.set_option('display.max_columns',None)

In [17]:
np.random.seed(0)

In [18]:
df.head()

,Unnamed: 0,Artist,Title,Top100,URI,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration,Time_Signature,lyrics,explicit,Release_Year,Genre
0,1,linkin park,in the end,0,60a0Rd6pjrkxjPbaKzXjfq,0.556,0.864,3,-5.870,0,0.0584,0.009580,0.000000,0.209,0.400,105.143,216880,4,It starts with\nOne thing I don't know why\nIt...,0.0,2000,metal
1,2,the white stripes,seven nation army,0,7i6r9KotUPQg3ozKKgEPIN,0.737,0.463,0,-7.828,1,0.0792,0.008170,0.447000,0.255,0.324,123.881,231733,4,I'm gonna fight 'em all\nA seven nation army c...,1.0,2003,rock
2,3,red hot chili peppers,by the way,0,3ZOEytgrvLwQaqXreDs2Jx,0.618,0.938,9,-3.442,1,0.0456,0.017900,0.000000,0.167,0.875,91.455,269000,4,Standing in line\nTo see the show tonight\nAnd...,1.0,2002,rock
3,5,evanescence,bring me to life,0,0COqiPhxzoWICwFCS4eZcp,0.331,0.943,4,-3.188,0,0.0698,0.007210,0.000002,0.242,0.296,94.612,235893,4,"How can you see into my eyes, like open doors?...",0.0,2003,alternative
4,6,papa roach,last resort,0,5W8YXBz9MTIDyrpYaCg2Ky,0.589,0.890,4,-3.719,0,0.0603,0.000481,0.000820,0.201,0.692,90.598,199907,4,Cut my life into pieces\nThis is my last resor...,1.0,2001,metal

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9226 entries, 0 to 9225
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        9226 non-null   int64
 1   Artist            9226 non-null   object
 2   Title             9226 non-null   object
 3   Top100            9226 non-null   int64
 4   URI               9226 non-null   object
 5   Danceability      9226 non-null   float64
 6   Energy            9226 non-null   float64
 7   Key               9226 non-null   int64
 8   Loudness          9226 non-null   float64
 9   Mode              9226 non-null   int64
 10  Speechiness       9226 non-null   float64
 11  Acousticness      9226 non-null   float64
 12  Instrumentalness  9226 non-null   float64
 13  Liveness          9226 non-null   float64
 14  Valence           9226 non-null   float64
 15  Tempo             9226 non-null   float64
 16  Duration          9226 non-null   int64
 17  Time_Signature    9226 non-null   int64
 18  lyrics            8801 non-null   object
 19  explicit          9226 non-null   float64
 20  Release_Year      9226 non-null   int64
 21  Genre             9226 non-null   object
dtypes: float64(10), int64(7), object(5)
memory usage: 1.5+ MB

In [20]:
df.describe()

,Unnamed: 0,Top100,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration,Time_Signature,explicit,Release_Year
count,9226.000000,9226.000000,9226.000000,9226.000000,9226.000000,9226.000000,9226.000000,9226.000000,9226.000000,9226.000000,9226.000000,9226.000000,9226.000000,9.226000e+03,9226.000000,9226.000000,9226.000000
mean,7525.648060,0.162692,0.624711,0.662369,5.334815,-7.097625,0.644917,0.095369,0.234841,0.040521,0.181757,0.536754,121.393626,2.244141e+05,3.959462,0.329287,2007.549426
std,4526.901432,0.369105,0.154501,0.205162,3.582050,3.367559,0.478565,0.095961,0.274592,0.149607,0.145542,0.240879,28.629974,5.722612e+04,0.289816,0.469980,13.697807
min,1.000000,0.000000,0.061700,0.002890,0.000000,-36.729000,0.000000,0.022800,0.000001,0.000000,0.011900,0.024600,46.591000,5.521300e+04,1.000000,0.000000,1945.000000
25%,3420.250000,0.000000,0.526000,0.525000,2.000000,-8.674000,0.000000,0.036400,0.019225,0.000000,0.092700,0.349000,98.807000,1.913730e+05,4.000000,0.000000,2002.000000
50%,7458.500000,0.000000,0.632000,0.694000,5.000000,-6.316500,1.000000,0.052700,0.111000,0.000005,0.123000,0.535000,120.032500,2.176145e+05,4.000000,0.000000,2014.000000
75%,11592.000000,0.000000,0.736000,0.827000,8.000000,-4.782250,1.000000,0.108750,0.370750,0.000888,0.229000,0.733000,139.846500,2.491420e+05,4.000000,1.000000,2018.000000
max,14733.000000,1.000000,0.981000,0.997000,11.000000,1.342000,1.000000,0.869000,0.996000,0.982000,0.986000,0.990000,216.115000,1.799347e+06,5.000000,1.000000,2020.000000

CHECKING NULL VALUES

In [21]:
df.isnull().sum()

Unnamed: 0            0
Artist                0
Title                 0
Top100                0
URI                   0
Danceability          0
Energy                0
Key                   0
Loudness              0
Mode                  0
Speechiness           0
Acousticness          0
Instrumentalness      0
Liveness              0
Valence               0
Tempo                 0
Duration              0
Time_Signature        0
lyrics              425
explicit              0
Release_Year          0
Genre                 0
dtype: int64

In [22]:
#dropping lyrics column as it contains null values
#dropping unnamed column and uri column

In [23]:
df.drop(['Unnamed: 0','lyrics','URI'],axis=1,inplace=True)

In [24]:
#dropping duplicate rows

In [25]:
temp=df[df['Title'].duplicated()]

In [26]:
#finding unique songs

In [40]:
list_of_songs=list(temp.Title.unique())

In [28]:
# filtering songs with same title but by different artists

In [31]:
n=[]
for i in range (len(list_of_songs)):
    m=(list(df[df['Title']==list_of_songs[i]]['Artist'])) # getting all artists of duplicate songs
    if m[0]==m[1]:
        pass
    else:
        j=(df[df['Title']==list_of_songs[i]].index) # if the artist is different , get the index of first artist
        n.append(j[0])

In [32]:
df1=df.iloc[n]

In [33]:
#dropping duplicate values
df2=df.drop_duplicates(subset='Title',keep='last')

In [34]:
#concatenating two dataframes

data=pd.concat([df1,df2])

In [35]:
data.reset_index(inplace=True,drop=True)

In [36]:
data.head()

,Artist,Title,Top100,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration,Time_Signature,explicit,Release_Year,Genre
0,bruce springsteen,dancing in the dark,0,0.527,0.942,1,-5.640,0,0.0366,0.011500,0.000000,0.1880,0.495,148.723,241307,4,0.0,1984,rock
1,the coral,in the morning,0,0.644,0.777,6,-6.165,0,0.0284,0.025200,0.000000,0.0554,0.966,126.257,152520,4,0.0,2005,rock
2,seether,remedy,0,0.550,0.952,8,-4.664,1,0.0924,0.000193,0.000666,0.0614,0.391,127.804,207213,4,0.0,2005,metal
3,janis joplin,me and bobby mcgee,0,0.453,0.464,2,-10.960,1,0.0431,0.302000,0.000060,0.1520,0.658,93.190,271333,4,0.0,1971,rock
4,i.o.i,pick me,0,0.686,0.885,9,-4.828,1,0.0868,0.004190,0.000265,0.1900,0.604,127.957,226874,4,0.0,2016,pop

In [38]:
data.shape

(9150, 19)

In [41]:
data.tail()

,Artist,Title,Top100,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration,Time_Signature,explicit,Release_Year,Genre
9145,daddy yankee,dura,1,0.783,0.840,1,-3.416,1,0.0510,0.17400,0.0,0.4120,0.839,95.001,200480,4,0.0,2018,reggae
9146,xxxtentacion,changes,1,0.669,0.308,11,-10.068,1,0.0290,0.88300,0.0,0.0984,0.520,64.934,121887,4,0.0,2018,rap
9147,luke combs,one number away,1,0.544,0.781,6,-6.160,0,0.0311,0.00585,0.0,0.1910,0.527,144.075,221800,4,0.0,2017,country
9148,rae sremmurd,powerglide,1,0.713,0.831,1,-4.750,0,0.1500,0.01680,0.0,0.1180,0.584,173.948,332301,4,1.0,2018,rap
9149,dua lipa,idgaf,1,0.836,0.544,7,-5.975,1,0.0943,0.04030,0.0,0.0824,0.510,97.028,217947,4,1.0,2017,pop

Distributions of Features with respect to time

INSTRUMENTALNESS

In [56]:
temp1=df[df['Release_Year'].isin(range(1990,2000))]
temp2=df[df['Release_Year'].isin(range(2000,2010))]
temp3=df[df['Release_Year'].isin(range(2010,2020))]